# Making Search Engine

In [85]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

import requests

In [71]:
import requests 

docs_url = 'https://github.com/alexeygrigorev/llm-rag-workshop/raw/main/notebooks/documents.json'
docs_response = requests.get(docs_url)
documents_raw = docs_response.json()

documents = []

for course in documents_raw:
    course_name = course['course']

    for doc in course['documents']:
        doc['course'] = course_name
        documents.append(doc)

In [72]:
df = pd.DataFrame(documents, columns=['course', 'section', 'question', 'text'])
df.head()

,course,section,question,text
0,data-engineering-zoomcamp,General course-related questions,Course - When will the course start?,The purpose of this document is to capture fre...
1,data-engineering-zoomcamp,General course-related questions,Course - What are the prerequisites for this c...,GitHub - DataTalksClub data-engineering-zoomca...
2,data-engineering-zoomcamp,General course-related questions,Course - Can I still join the course after the...,"Yes, even if you don't register, you're still ..."
3,data-engineering-zoomcamp,General course-related questions,Course - I have registered for the Data Engine...,You don't need it. You're accepted. You can al...
4,data-engineering-zoomcamp,General course-related questions,Course - What can I do before the course starts?,You can start by installing and setting up all...

In [73]:
df[df.course == 'data-engineering-zoomcamp'].head()

,course,section,question,text
0,data-engineering-zoomcamp,General course-related questions,Course - When will the course start?,The purpose of this document is to capture fre...
1,data-engineering-zoomcamp,General course-related questions,Course - What are the prerequisites for this c...,GitHub - DataTalksClub data-engineering-zoomca...
2,data-engineering-zoomcamp,General course-related questions,Course - Can I still join the course after the...,"Yes, even if you don't register, you're still ..."
3,data-engineering-zoomcamp,General course-related questions,Course - I have registered for the Data Engine...,You don't need it. You're accepted. You can al...
4,data-engineering-zoomcamp,General course-related questions,Course - What can I do before the course starts?,You can start by installing and setting up all...

In [74]:
docs_example = [
    "Course starts on 15th Jan 2024",
    "Prerequisites listed on GitHub",
    "Submit homeworks after start date",
    "Registration not required for participation",
    "Setup Google Cloud and Python before course"
]

In [75]:
cv = TfidfVectorizer(stop_words='english', min_df=5)
X = cv.fit_transform(df.text)

names = cv.get_feature_names_out()

df_docs = pd.DataFrame(X.toarray(), columns=names).T
df_docs.round(2)

,0,1,2,3,4,5,6,7,8,9,...,938,939,940,941,942,943,944,945,946,947
01,0.0,0.00,0.00,0.0,0.0,0.00,0.00,0.0,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00
02,0.0,0.00,0.00,0.0,0.0,0.00,0.00,0.0,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00
03,0.0,0.00,0.00,0.0,0.0,0.00,0.00,0.0,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00
04,0.0,0.00,0.00,0.0,0.0,0.00,0.00,0.0,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00
05,0.0,0.00,0.00,0.0,0.0,0.00,0.00,0.0,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
yes,0.0,0.00,0.28,0.0,0.0,0.00,0.21,0.2,0.15,0.00,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00
yml,0.0,0.00,0.00,0.0,0.0,0.00,0.00,0.0,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.11,0.0,0.0,0.0,0.00
youtube,0.0,0.00,0.00,0.0,0.0,0.00,0.00,0.0,0.00,0.15,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00
zip,0.0,0.00,0.00,0.0,0.0,0.00,0.00,0.0,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00
zoomcamp,0.0,0.43,0.00,0.0,0.0,0.19,0.00,0.0,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.15

In [76]:
query = "Do I need to know python to sign up for the January course?"

q = cv.transform([query])
q.toarray()

array([[0., 0., 0., ..., 0., 0., 0.]], shape=(1, 1333))

In [78]:
query_dict = dict(zip(names, q.toarray()[0]))
query_dict

{'01': np.float64(0.0),
 '02': np.float64(0.0),
 '03': np.float64(0.0),
 '04': np.float64(0.0),
 '05': np.float64(0.0),
 '06': np.float64(0.0),
 '09': np.float64(0.0),
 '10': np.float64(0.0),
 '100': np.float64(0.0),
 '11': np.float64(0.0),
 '12': np.float64(0.0),
 '127': np.float64(0.0),
 '13': np.float64(0.0),
 '14': np.float64(0.0),
 '15': np.float64(0.0),
 '16': np.float64(0.0),
 '17': np.float64(0.0),
 '19': np.float64(0.0),
 '1st': np.float64(0.0),
 '20': np.float64(0.0),
 '2019': np.float64(0.0),
 '2020': np.float64(0.0),
 '2021': np.float64(0.0),
 '2022': np.float64(0.0),
 '2023': np.float64(0.0),
 '2024': np.float64(0.0),
 '21': np.float64(0.0),
 '22': np.float64(0.0),
 '24': np.float64(0.0),
 '25': np.float64(0.0),
 '2pacx': np.float64(0.0),
 '30': np.float64(0.0),
 '35': np.float64(0.0),
 '403': np.float64(0.0),
 '42': np.float64(0.0),
 '50': np.float64(0.0),
 '5000': np.float64(0.0),
 '5431': np.float64(0.0),
 '5432': np.float64(0.0),
 '60': np.float64(0.0),
 '600': np.float64(0.0),
 '7077': np.float64(0.0),
 '80': np.float64(0.0),
 '8080': np.float64(0.0),
 '8888': np.float64(0.0),
 '9696': np.float64(0.0),
 'abhijit': np.float64(0.0),
 'able': np.float64(0.0),
 'abolade': np.float64(0.0),
 'absolute': np.float64(0.0),
 'accept': np.float64(0.0),
 'access': np.float64(0.0),
 'accordingly': np.float64(0.0),
 'account': np.float64(0.0),
 'accuracy': np.float64(0.0),
 'action': np.float64(0.0),
 'activate': np.float64(0.0),
 'actual': np.float64(0.0),
 'actually': np.float64(0.0),
 'add': np.float64(0.0),
 'added': np.float64(0.0),
 'adding': np.float64(0.0),
 'addition': np.float64(0.0),
 'additional': np.float64(0.0),
 'additionally': np.float64(0.0),
 'address': np.float64(0.0),
 'admin': np.float64(0.0),
 'advani': np.float64(0.0),
 'ahmed': np.float64(0.0),
 'ai': np.float64(0.0),
 'airflow': np.float64(0.0),
 'alejandro': np.float64(0.0),
 'alena': np.float64(0.0),
 'alex': np.float64(0.0),
 'alexey': np.float64(0.0),
 'alexeygrigorev': np.float64(0.0),
 'allocate': np.float64(0.0),
 'allow': np.float64(0.0),
 'allowed': np.float64(0.0),
 'allowing': np.float64(0.0),
 'allows': np.float64(0.0),
 'alpha': np.float64(0.0),
 'alternative': np.float64(0.0),
 'alternatively': np.float64(0.0),
 'amazon': np.float64(0.0),
 'amazonaws': np.float64(0.0),
 'amd64': np.float64(0.0),
 'aminat': np.float64(0.0),
 'anaconda': np.float64(0.0),
 'anaconda3': np.float64(0.0),
 'analytics': np.float64(0.0),
 'anand': np.float64(0.0),
 'andrii': np.float64(0.0),
 'ans': np.float64(0.0),
 'answer': np.float64(0.0),
 'answered': np.float64(0.0),
 'answers': np.float64(0.0),
 'apache': np.float64(0.0),
 'api': np.float64(0.0),
 'aponte': np.float64(0.0),
 'app': np.float64(0.0),
 'appear': np.float64(0.0),
 'appears': np.float64(0.0),
 'append': np.float64(0.0),
 'application': np.float64(0.0),
 'apply': np.float64(0.0),
 'appname': np.float64(0.0),
 'approach': np.float64(0.0),
 'apt': np.float64(0.0),
 'architecture': np.float64(0.0),
 'archives': np.float64(0.0),
 'args': np.float64(0.0),
 'argument': np.float64(0.0),
 'array': np.float64(0.0),
 'arrays': np.float64(0.0),
 'article': np.float64(0.0),
 'asia': np.float64(0.0),
 'ask': np.float64(0.0),
 'asked': np.float64(0.0),
 'asks': np.float64(0.0),
 'assigned': np.float64(0.0),
 'astype': np.float64(0.0),
 'attempting': np.float64(0.0),
 'attribute': np.float64(0.0),
 'attributeerror': np.float64(0.0),
 'auc': np.float64(0.0),
 'auth': np.float64(0.0),
 'authenticate': np.float64(0.0),
 'authentication': np.float64(0.0),
 'auto': np.float64(0.0),
 'automatically': np.float64(0.0),
 'available': np.float64(0.0),
 'average': np.float64(0.0),
 'avila': np.float64(0.0),
 'avoid': np.float64(0.0),
 'aws': np.float64(0.0),
 'azure': np.float64(0.0),
 'backend': np.float64(0.0),
 'bad': np.float64(0.0),
 'bar': np.float64(0.0),
 'base': np.float64(0.0),
 'based': np.float64(0.0),
 'bash': np.float64(0.0),
 'bashrc': np.float64(0.0),
 'basically': np.float64(0.0),
 'batch': np.float64(0.0),
 'best': np.float64(0.0),
 'better': np.float64(0.0),
 'bhaskar': np.float64(0.0),
 'bhatia': np.float64(0.0),
 'big': np.float64(0.0),
 'bigquery': np.float64(0.0),
 'billing': np.float64(0.0),
 'bin': np.float64(0.0),
 'binary': np.float64(0.0),
 'bind': np.float64(0.0),
 'bit': np.float64(0.0),
 'blob': np.float64(0.0),
 'block': np.float64(0.0),
 'blog': np.float64(0.0),
 'box': np.float64(0.0),
 'bq': np.float64(0.0),
 'branch': np.float64(0.0),
 'brew': np.float64(0.0),
 'brigida': np.float64(0.0),
 'browser': np.float64(0.0),
 'bucket': np.float64(0.0),
 'build': np.float64(0.0),
 'builder': np.float64(0.0),
 'building': np.float64(0.0),
 'built': np.float64(0.0),
 'calculate': np.float64(0.0),
 'calderin': np.float64(0.0),
 'called': np.float64(0.0),
 'calling': np.float64(0.0),
 'capstone': np.float64(0.0),
 'capture': np.float64(0.0),
 'care': np.float64(0.0),
 'careful': np.float64(0.0),
 'case': np.float64(0.0),
 'cast': np.float64(0.0),
 'cat': np.float64(0.0),
 'categorical': np.float64(0.0),
 'cause': np.float64(0.0),
 'caused': np.float64(0.0),
 'causing': np.float64(0.0),
 'cd': np.float64(0.0),
 'cell': np.float64(0.0),
 'certificate': np.float64(0.0),
 'chakraborty': np.float64(0.0),
 'change': np.float64(0.0),
 'changed': np.float64(0.0),
 'changes': np.float64(0.0),
 'changing': np.float64(0.0),
 'channel': np.float64(0.0),
 'check': np.float64(0.0),
 'checking': np.float64(0.0),
 'chizhmak': np.float64(0.0),
 'chmod': np.float64(0.0),
 'choice': np.float64(0.0),
 'choose': np.float64(0.0),
 'chown': np.float64(0.0),
 'churn': np.float64(0.0),
 'ci': np.float64(0.0),
 'class': np.float64(0.0),
 'classes': np.float64(0.0),
 'classification': np.float64(0.0),
 'clear': np.float64(0.0),
 'cli': np.float64(0.0),
 'click': np.float64(0.0),
 'client': np.float64(0.0),
 'clone': np.float64(0.0),
 'close': np.float64(0.0),
 'closed': np.float64(0.0),
 'closest': np.float64(0.0),
 'clothing': np.float64(0.0),
 'cloud': np.float64(0.0),
 'cloudfront': np.float64(0.0),
 'club': np.float64(0.0),
 'cluster': np.float64(0.0),
 'cmd': np.float64(0.0),
 'code': np.float64(0.0),
 'codespaces': np.float64(0.0),
 'coding': np.float64(0.0),
 'cohort': np.float64(0.0),
 'cohorts': np.float64(0.0),
 'col': np.float64(0.0),
 'colab': np.float64(0.0),
 'column': np.float64(0.0),
 'columns': np.float64(0.0),
 'com': np.float64(0.0),
 'command': np.float64(0.0),
 'commands': np.float64(0.0),
 'commit': np.float64(0.0),
 'common': np.float64(0.0),
 'community': np.float64(0.0),
 'compatibility': np.float64(0.0),
 'compatible': np.float64(0.0),
 'complete': np.float64(0.0),
 'completed': np.float64(0.0),
 'compose': np.float64(0.0),
 'compute': np.float64(0.0),
 'computer': np.float64(0.0),
 'conda': np.float64(0.0),
 'config': np.float64(0.0),
 'configuration': np.float64(0.0),
 'configure': np.float64(0.0),
 'configured': np.float64(0.0),
 'confirm': np.float64(0.0),
 'connect': np.float64(0.0),
 'connecting': np.float64(0.0),
 'connection': np.float64(0.0),
 'connector': np.float64(0.0),
 'consider': np.float64(0.0),
 'consistent': np.float64(0.0),
 'console': np.float64(0.0),
 'contain': np.float64(0.0),
 'container': np.float64(0.0),
 'containers': np.float64(0.0),
 'contains': np.float64(0.0),
 'content': np.float64(0.0),
 'contents': np.float64(0.0),
 'context': np.float64(0.0),
 'continue': np.float64(0.0),
 'control': np.float64(0.0),
 'convert': np.float64(0.0),
 'converted': np.float64(0.0),
 'copy': np.float64(0.0),
 'core': np.float64(0.0),
 'correct': np.float64(0.0),
 'correctly': np.float64(0.0),
 'correlation': np.float64(0.0),
 'corresponding': np.float64(0.0),
 'couldn': np.float64(0.0),
 'course': np.float64(0.38148200594064524),
 'cp': np.float64(0.0),
 'cpu': np.float64(0.0),
 'create': np.float64(0.0),
 'create_engine': np.float64(0.0),
 'created': np.float64(0.0),
 'creates': np.float64(0.0),
 'creating': np.float64(0.0),
 'creation': np.float64(0.0),
 'credentials': np.float64(0.0),
 'credit': np.float64(0.0),
 'crucial': np.float64(0.0),
 'csv': np.float64(0.0),
 'ctrl': np.float64(0.0),
 'curl': np.float64(0.0),
 'current': np.float64(0.0),
 'custom': np.float64(0.0),
 'd37ci6vzurychx': np.float64(0.0),
 'daemon': np.float64(0.0),
 'daniel': np.float64(0.0),
 'dashboard': np.float64(0.0),
 'data': np.float64(0.0),
 'database': np.float64(0.0),
 'dataframe': np.float64(0.0),
 'dataframes': np.float64(0.0),
 'dataproc': np.float64(0.0),
 'dataset': np.float64(0.0),
 'datasets': np.float64(0.0),
 'datatalks': np.float64(0.0),
 'datatalksclub': np.float64(0.0),
 'datatype': np.float64(0.0),
 'date': np.float64(0.0),
 'datetime': np.float64(0.0),
 'david': np.float64(0.0),
 'day': np.float64(0.0),
 'db': np.float64(0.0),
 'dbt': np.float64(0.0),
 'dbt_project': np.float64(0.0),
 'deadline': np.float64(0.0),
 'dealing': np.float64(0.0),
 'debian': np.float64(0.0),
 'debug': np.float64(0.0),
 'deep': np.float64(0.0),
 'def': np.float64(0.0),
 'default': np.float64(0.0),
 'define': np.float64(0.0),
 'defined': np.float64(0.0),
 'definition': np.float64(0.0),
 'delete': np.float64(0.0),
 'deleted': np.float64(0.0),
 'deleting': np.float64(0.0),
 'denied': np.float64(0.0),
 'dependencies': np.float64(0.0),
 'dependency': np.float64(0.0),
 'deploy': np.float64(0.0),
 'deploying': np.float64(0.0),
 'deployment': np.float64(0.0),
 'deprecated': np.float64(0.0),
 'description': np.float64(0.0),
 'desktop': np.float64(0.0),
 'detailed': np.float64(0.0),
 'details': np.float64(0.0),
 'dev': np.float64(0.0),
 'development': np.float64(0.0),
 'deviation': np.float64(0.0),
 'device': np.float64(0.0),
 'df': np.float64(0.0),
 'df_train': np.float64(0.0),
 'dict': np.float64(0.0),
 'dictionary': np.float64(0.0),
 'dictvectorizer': np.float64(0.0),
 'did': np.float64(0.0),
 'didn': np.float64(0.0),
 'difference': np.float64(0.0),
 'different': np.float64(0.0),
 'dino': np.float64(0.0),
 'dir': np.float64(0.0),
 'directly': np.float64(0.0),
 'directory': np.float64(0.0),
 'disk': np.float64(0.0),
 'distribution': np.float64(0.0),
 'doc': np.float64(0.0),
 'docker': np.float64(0.0),
 'dockerfile': np.float64(0.0),
 'docs': np.float64(0.0),
 'document': np.float64(0.0),
 'documentation': np.float64(0.0),
 'does': np.float64(0.0),
 'doesn': np.float64(0.0),
 'doing': np.float64(0.0),
 'dolocationid': np.float64(0.0),
 'don': np.float64(0.0),
 'dot': np.float64(0.0),
 'double': np.float64(0.0),
 'downgrade': np.float64(0.0),
 'download': np.float64(0.0),
 'downloaded': np.float64(0.0),
 'downloading': np.float64(0.0),
 'downloads': np.float64(0.0),
 'dpage': np.float64(0.0),
 'dragon': np.float64(0.0),
 'drive': np.float64(0.0),
 'drop': np.float64(0.0),
 'dropoff_datetime': np.float64(0.0),
 'dropping': np.float64(0.0),
 'dt': np.float64(0.0),
 'dtc': np.float64(0.0),
 'duration': np.float64(0.0),
 'dv': np.float64(0.0),
 'easier': np.float64(0.0),
 'easiest': np.float64(0.0),
 'easily': np.float64(0.0),
 'ec2': np.float64(0.0),
 'echo': np.float64(0.0),
 'ecr': np.float64(0.0),
 'edit': np.float64(0.0),
 'editing': np.float64(0.0),
 'editor': np.float64(0.0),
 'email': np.float64(0.0),
 'en': np.float64(0.0),
 'enable': np.float64(0.0),
 'enabled': np.float64(0.0),
 'encode': np.float64(0.0),
 'encoding': np.float64(0.0),
 'encounter': np.float64(0.0),
 'encountered': np.float64(0.0),
 'end': np.float64(0.0),
 'endpoint': np.float64(0.0),
 'engine': np.float64(0.0),
 'engineering': np.float64(0.0),
 'ensure': np.float64(0.0),
 'enter': np.float64(0.0),
 'entire': np.float64(0.0),
 'entries': np.float64(0.0),
 'env': np.float64(0.0),
 'environ': np.float64(0.0),
 'environment': np.float64(0.0),
 'environments': np.float64(0.0),
 'equal': np.float64(0.0),
 'erick': np.float64(0.0),
 'error': np.float64(0.0),
 'errors': np.float64(0.0),
 'escape': np.float64(0.0),
 'especially': np.float64(0.0),
 'eu': np.float64(0.0),
 'europe': np.float64(0.0),
 'evaluate': np.float64(0.0),
 'evaluated': np.float64(0.0),
 'evaluation': np.float64(0.0),
 'exactly': np.float64(0.0),
 'example': np.float64(0.0),
 'exception': np.float64(0.0),
 'exe': np.float64(0.0),
 'exec': np.float64(0.0),
 'executable': np.float64(0.0),
 'execute': np.float64(0.0),
 'executed': np.float64(0.0),
 'executing': np.float64(0.0),
 'execution': np.float64(0.0),
 'exist': np.float64(0.0),
 'existing': np.float64(0.0),
 'exists': np.float64(0.0),
 'exit': np.float64(0.0),
 'expected': np.float64(0.0),
 'experiment': np.float64(0.0),
 'explanation': np.float64(0.0),
 'explicitly': np.float64(0.0),
 'export': np.float64(0.0),
 'extension': np.float64(0.0),
 'external': np.float64(0.0),
 'extra': np.float64(0.0),
 'extract': np.float64(0.0),
 'face': np.float64(0.0),
 'faced': np.float64(0.0),
 'fact': np.float64(0.0),
 'fact_trips': np.float64(0.0),
 'fail': np.float64(0.0),
 'failed': np.float64(0.0),
 'failing': np.float64(0.0),
 'fails': np.float64(0.0),
 'false': np.float64(0.0),
 'faq': np.float64(0.0),
 'fatal': np.float64(0.0),
 'feature': np.float64(0.0),
 'features': np.float64(0.0),
 'fetch': np.float64(0.0),
 'fhv': np.float64(0.0),
 'fhv_tripdata_2019': np.float64(0.0),
 'field': np.float64(0.0),
 'figure': np.float64(0.0),
 'file': np.float64(0.0),
 'files': np.float64(0.0),
 'filesystem': np.float64(0.0),
 'filter': np.float64(0.0),
 'final': np.float64(0.0),
 'finally': np.float64(0.0),
 'findspark': np.float64(0.0),
 'fine': np.float64(0.0),
 'fit': np.float64(0.0),
 'fix': np.float64(0.0),
 'fixed': np.float64(0.0),
 'flag': np.float64(0.0),
 'flask': np.float64(0.0),
 'float': np.float64(0.0),
 'float64': np.float64(0.0),
 'flow': np.float64(0.0),
 'folder': np.float64(0.0),
 'folders': np.float64(0.0),
 'follow': np.float64(0.0),
 'followed': np.float64(0.0),
 'following': np.float64(0.0),
 'follows': np.float64(0.0),
 'forbidden': np.float64(0.0),
 'force': np.float64(0.0),
 'forget': np.float64(0.0),
 'forgot': np.float64(0.0),
 'form': np.float64(0.0),
 'format': np.float64(0.0),
 'forms': np.float64(0.0),
 'forward': np.float64(0.0),
 'fouesnard': np.float64(0.0),
 'free': np.float64(0.0),
 'fresh': np.float64(0.0),
 'fs': np.float64(0.0),
 'function': np.float64(0.0),
 'functions': np.float64(0.0),
 'future': np.float64(0.0),
 'gateway': np.float64(0.0),
 'gcloud': np.float64(0.0),
 'gcp': np.float64(0.0),
 'gcs': np.float64(0.0),
 'generate': np.float64(0.0),
 'generated': np.float64(0.0),
 'generator': np.float64(0.0),
 'george': np.float64(0.0),
 'get_dummies': np.float64(0.0),
 'get_feature_names_out': np.float64(0.0),
 'getdbt': np.float64(0.0),
 'getorcreate': np.float64(0.0),
 'gets': np.float64(0.0),
 'getting': np.float64(0.0),
 'git': np.float64(0.0),
 'github': np.float64(0.0),
 'githubusercontent': np.float64(0.0),
 'gitignore': np.float64(0.0),
 'given': np.float64(0.0),
 'gives': np.float64(0.0),
 'gmail': np.float64(0.0),
 'going': np.float64(0.0),
 'good': np.float64(0.0),
 'google': np.float64(0.0),
 'google_application_credentials': np.float64(0.0),
 'googleapi': np.float64(0.0),
 'googleapis': np.float64(0.0),
 'got': np.float64(0.0),
 'gpu': np.float64(0.0),
 'great': np.float64(0.0),
 'green': np.float64(0.0),
 'grigorev': np.float64(0.0),
 'group': np.float64(0.0),
 'gs': np.float64(0.0),
 'guide': np.float64(0.0),
 'gunicorn': np.float64(0.0),
 'gz': np.float64(0.0),
 'gzip': np.float64(0.0),
 'hadoop': np.float64(0.0),
 'hadoop3': np.float64(0.0),
 'hand': np.float64(0.0),
 'handle': np.float64(0.0),
 'happen': np.float64(0.0),
 'happens': np.float64(0.0),
 'haven': np.float64(0.0),
 'having': np.float64(0.0),
 'head': np.float64(0.0),
 'help': np.float64(0.0),
 'helped': np.float64(0.0),
 'helps': np.float64(0.0),
 'high': np.float64(0.0),
 'higher': np.float64(0.0),
 'highly': np.float64(0.0),
 'home': np.float64(0.0),
 'homebrew': np.float64(0.0),
 'homework': np.float64(0.0),
 'homeworks': np.float64(0.0),
 'hope': np.float64(0.0),
 'host': np.float64(0.0),
 'hostname': np.float64(0.0),
 'hot': np.float64(0.0),
 'hours': np.float64(0.0),
 'housing': np.float64(0.0),
 'hrithik': np.float64(0.0),
 'html': np.float64(0.0),
 'http': np.float64(0.0),
 'https': np.float64(0.0),
 'humberto': np.float64(0.0),
 'hw': np.float64(0.0),
 'hws': np.float64(0.0),
 'iam': np.float64(0.0),
 'icon': np.float64(0.0),
 'id': np.float64(0.0),
 'ide': np.float64(0.0),
 'idea': np.float64(0.0),
 'ignore': np.float64(0.0),
 'image': np.float64(0.0),
 'images': np.float64(0.0),
 'immediately': np.float64(0.0),
 'import': np.float64(0.0),
 'importance': np.float64(0.0),
 'important': np.float64(0.0),
 'importerror': np.float64(0.0),
 'importing': np.float64(0.0),
 'include': np.float64(0.0),
 'included': np.float64(0.0),
 'including': np.float64(0.0),
 'increase': np.float64(0.0),
 'index': np.float64(0.0),
 'info': np.float64(0.0),
 'information': np.float64(0.0),
 'init': np.float64(0.0),
 'initial': np.float64(0.0),
 'input': np.float64(0.0),
 'inside': np.float64(0.0),
 'install': np.float64(0.0),
 'installation': np.float64(0.0),
 'installed': np.float64(0.0),
 'installing': np.float64(0.0),
 'instance': np.float64(0.0),
 'instances': np.float64(0.0),
 'instead': np.float64(0.0),
 'instruction': np.float64(0.0),
 'instructions': np.float64(0.0),
 'insufficient': np.float64(0.0),
 'int': np.float64(0.0),
 'int64': np.float64(0.0),
 'integer': np.float64(0.0),
 'interesting': np.float64(0.0),
 'interface': np.float64(0.0),
 'internal': np.float64(0.0),
 'internet': np.float64(0.0),
 'interpreter': np.float64(0.0),
 'intro': np.float64(0.0),
 'invalid': np.float64(0.0),
 'io': np.float64(0.0),
 'ip': np.float64(0.0),
 'ipynb': np.float64(0.0),
 'isn': np.float64(0.0),
 'issue': np.float64(0.0),
 'issues': np.float64(0.0),
 'iteration': np.float64(0.0),
 'ivan': np.float64(0.0),
 'jan': np.float64(0.0),
 'jar': np.float64(0.0),
 'java': np.float64(0.0),
 'java_home': np.float64(0.0),
 'job': np.float64(0.0),
 'jobs': np.float64(0.0),
 'join': np.float64(0.0),
 'json': np.float64(0.0),
 'jupyter': np.float64(0.0),
 'just': np.float64(0.0),
 'kafka': np.float64(0.0),
 'kaggle': np.float64(0.0),
 'keras': np.float64(0.0),
 'kernel': np.float64(0.0),
 'key': np.float64(0.0),
 'keys': np.float64(0.0),
 'kill': np.float64(0.0),
 'kind': np.float64(0.0),
 'kinesis': np.float64(0.0),
 'kniazeva': np.float64(0.0),
 'know': np.float64(0.5608269127690405),
 'known': np.float64(0.0),
 'konrad': np.float64(0.0),
 'krishna': np.float64(0.0),
 'kubectl': np.float64(0.0),
 'kubernetes': np.float64(0.0),
 'kumar': np.float64(0.0),
 'kwargs': np.float64(0.0),
 'lambda': np.float64(0.0),
 'laptop': np.float64(0.0),
 'large': np.float64(0.0),
 'larkin': np.float64(0.0),
 'later': np.float64(0.0),
 'latest': np.float64(0.0),
 'launch': np.float64(0.0),
 'layer': np.float64(0.0),
 'layers': np.float64(0.0),
 'lead': np.float64(0.0),
 'leaderboard': np.float64(0.0),
 'learn': np.float64(0.0),
 'learning': np.float64(0.0),
 'left': np.float64(0.0),
 'length': np.float64(0.0),
 'lesson': np.float64(0.0),
 'lessons': np.float64(0.0),
 'let': np.float64(0.0),
 'level': np.float64(0.0),
 'lib': np.float64(0.0),
 'libraries': np.float64(0.0),
 'library': np.float64(0.0),
 'like': np.float64(0.0),
 'likely': np.float64(0.0),
 'line': np.float64(0.0),
 'linear': np.float64(0.0),
 'lines': np.float64(0.0),
 'link': np.float64(0.0),
 'links': np.float64(0.0),
 'linux': np.float64(0.0),
 'list': np.float64(0.0),
 'listed': np.float64(0.0),
 'litvinov': np.float64(0.0),
 'live': np.float64(0.0),
 'll': np.float64(0.0),
 'load': np.float64(0.0),
 'loaded': np.float64(0.0),
 'loading': np.float64(0.0),
 'local': np.float64(0.0),
 'localhost': np.float64(0.0),
 'locally': np.float64(0.0),
 'located': np.float64(0.0),
 'location': np.float64(0.0),
 'locations': np.float64(0.0),
 'lock': np.float64(0.0),
 'log': np.float64(0.0),
 'logged': np.float64(0.0),
 'login': np.float64(0.0),
 'logistic': np.float64(0.0),
 'logs': np.float64(0.0),
 'long': np.float64(0.0),
 'longer': np.float64(0.0),
 'look': np.float64(0.0),

In [79]:
doc_dict = dict(zip(names, X.toarray()[1]))
doc_dict

{'01': np.float64(0.0),
 '02': np.float64(0.0),
 '03': np.float64(0.0),
 '04': np.float64(0.0),
 '05': np.float64(0.0),
 '06': np.float64(0.0),
 '09': np.float64(0.0),
 '10': np.float64(0.0),
 '100': np.float64(0.0),
 '11': np.float64(0.0),
 '12': np.float64(0.0),
 '127': np.float64(0.0),
 '13': np.float64(0.0),
 '14': np.float64(0.0),
 '15': np.float64(0.0),
 '16': np.float64(0.0),
 '17': np.float64(0.0),
 '19': np.float64(0.0),
 '1st': np.float64(0.0),
 '20': np.float64(0.0),
 '2019': np.float64(0.0),
 '2020': np.float64(0.0),
 '2021': np.float64(0.0),
 '2022': np.float64(0.0),
 '2023': np.float64(0.0),
 '2024': np.float64(0.0),
 '21': np.float64(0.0),
 '22': np.float64(0.0),
 '24': np.float64(0.0),
 '25': np.float64(0.0),
 '2pacx': np.float64(0.0),
 '30': np.float64(0.0),
 '35': np.float64(0.0),
 '403': np.float64(0.0),
 '42': np.float64(0.0),
 '50': np.float64(0.0),
 '5000': np.float64(0.0),
 '5431': np.float64(0.0),
 '5432': np.float64(0.0),
 '60': np.float64(0.0),
 '600': np.float64(0.0),
 '7077': np.float64(0.0),
 '80': np.float64(0.0),
 '8080': np.float64(0.0),
 '8888': np.float64(0.0),
 '9696': np.float64(0.0),
 'abhijit': np.float64(0.0),
 'able': np.float64(0.0),
 'abolade': np.float64(0.0),
 'absolute': np.float64(0.0),
 'accept': np.float64(0.0),
 'access': np.float64(0.0),
 'accordingly': np.float64(0.0),
 'account': np.float64(0.0),
 'accuracy': np.float64(0.0),
 'action': np.float64(0.0),
 'activate': np.float64(0.0),
 'actual': np.float64(0.0),
 'actually': np.float64(0.0),
 'add': np.float64(0.0),
 'added': np.float64(0.0),
 'adding': np.float64(0.0),
 'addition': np.float64(0.0),
 'additional': np.float64(0.0),
 'additionally': np.float64(0.0),
 'address': np.float64(0.0),
 'admin': np.float64(0.0),
 'advani': np.float64(0.0),
 'ahmed': np.float64(0.0),
 'ai': np.float64(0.0),
 'airflow': np.float64(0.0),
 'alejandro': np.float64(0.0),
 'alena': np.float64(0.0),
 'alex': np.float64(0.0),
 'alexey': np.float64(0.0),
 'alexeygrigorev': np.float64(0.0),
 'allocate': np.float64(0.0),
 'allow': np.float64(0.0),
 'allowed': np.float64(0.0),
 'allowing': np.float64(0.0),
 'allows': np.float64(0.0),
 'alpha': np.float64(0.0),
 'alternative': np.float64(0.0),
 'alternatively': np.float64(0.0),
 'amazon': np.float64(0.0),
 'amazonaws': np.float64(0.0),
 'amd64': np.float64(0.0),
 'aminat': np.float64(0.0),
 'anaconda': np.float64(0.0),
 'anaconda3': np.float64(0.0),
 'analytics': np.float64(0.0),
 'anand': np.float64(0.0),
 'andrii': np.float64(0.0),
 'ans': np.float64(0.0),
 'answer': np.float64(0.0),
 'answered': np.float64(0.0),
 'answers': np.float64(0.0),
 'apache': np.float64(0.0),
 'api': np.float64(0.0),
 'aponte': np.float64(0.0),
 'app': np.float64(0.0),
 'appear': np.float64(0.0),
 'appears': np.float64(0.0),
 'append': np.float64(0.0),
 'application': np.float64(0.0),
 'apply': np.float64(0.0),
 'appname': np.float64(0.0),
 'approach': np.float64(0.0),
 'apt': np.float64(0.0),
 'architecture': np.float64(0.0),
 'archives': np.float64(0.0),
 'args': np.float64(0.0),
 'argument': np.float64(0.0),
 'array': np.float64(0.0),
 'arrays': np.float64(0.0),
 'article': np.float64(0.0),
 'asia': np.float64(0.0),
 'ask': np.float64(0.0),
 'asked': np.float64(0.0),
 'asks': np.float64(0.0),
 'assigned': np.float64(0.0),
 'astype': np.float64(0.0),
 'attempting': np.float64(0.0),
 'attribute': np.float64(0.0),
 'attributeerror': np.float64(0.0),
 'auc': np.float64(0.0),
 'auth': np.float64(0.0),
 'authenticate': np.float64(0.0),
 'authentication': np.float64(0.0),
 'auto': np.float64(0.0),
 'automatically': np.float64(0.0),
 'available': np.float64(0.0),
 'average': np.float64(0.0),
 'avila': np.float64(0.0),
 'avoid': np.float64(0.0),
 'aws': np.float64(0.0),
 'azure': np.float64(0.0),
 'backend': np.float64(0.0),
 'bad': np.float64(0.0),
 'bar': np.float64(0.0),
 'base': np.float64(0.0),
 'based': np.float64(0.0),
 'bash': np.float64(0.0),
 'bashrc': np.float64(0.0),
 'basically': np.float64(0.0),
 'batch': np.float64(0.0),
 'best': np.float64(0.0),
 'better': np.float64(0.0),
 'bhaskar': np.float64(0.0),
 'bhatia': np.float64(0.0),
 'big': np.float64(0.0),
 'bigquery': np.float64(0.0),
 'billing': np.float64(0.0),
 'bin': np.float64(0.0),
 'binary': np.float64(0.0),
 'bind': np.float64(0.0),
 'bit': np.float64(0.0),
 'blob': np.float64(0.0),
 'block': np.float64(0.0),
 'blog': np.float64(0.0),
 'box': np.float64(0.0),
 'bq': np.float64(0.0),
 'branch': np.float64(0.0),
 'brew': np.float64(0.0),
 'brigida': np.float64(0.0),
 'browser': np.float64(0.0),
 'bucket': np.float64(0.0),
 'build': np.float64(0.0),
 'builder': np.float64(0.0),
 'building': np.float64(0.0),
 'built': np.float64(0.0),
 'calculate': np.float64(0.0),
 'calderin': np.float64(0.0),
 'called': np.float64(0.0),
 'calling': np.float64(0.0),
 'capstone': np.float64(0.0),
 'capture': np.float64(0.0),
 'care': np.float64(0.0),
 'careful': np.float64(0.0),
 'case': np.float64(0.0),
 'cast': np.float64(0.0),
 'cat': np.float64(0.0),
 'categorical': np.float64(0.0),
 'cause': np.float64(0.0),
 'caused': np.float64(0.0),
 'causing': np.float64(0.0),
 'cd': np.float64(0.0),
 'cell': np.float64(0.0),
 'certificate': np.float64(0.0),
 'chakraborty': np.float64(0.0),
 'change': np.float64(0.0),
 'changed': np.float64(0.0),
 'changes': np.float64(0.0),
 'changing': np.float64(0.0),
 'channel': np.float64(0.0),
 'check': np.float64(0.0),
 'checking': np.float64(0.0),
 'chizhmak': np.float64(0.0),
 'chmod': np.float64(0.0),
 'choice': np.float64(0.0),
 'choose': np.float64(0.0),
 'chown': np.float64(0.0),
 'churn': np.float64(0.0),
 'ci': np.float64(0.0),
 'class': np.float64(0.0),
 'classes': np.float64(0.0),
 'classification': np.float64(0.0),
 'clear': np.float64(0.0),
 'cli': np.float64(0.0),
 'click': np.float64(0.0),
 'client': np.float64(0.0),
 'clone': np.float64(0.0),
 'close': np.float64(0.0),
 'closed': np.float64(0.0),
 'closest': np.float64(0.0),
 'clothing': np.float64(0.0),
 'cloud': np.float64(0.0),
 'cloudfront': np.float64(0.0),
 'club': np.float64(0.0),
 'cluster': np.float64(0.0),
 'cmd': np.float64(0.0),
 'code': np.float64(0.0),
 'codespaces': np.float64(0.0),
 'coding': np.float64(0.0),
 'cohort': np.float64(0.0),
 'cohorts': np.float64(0.0),
 'col': np.float64(0.0),
 'colab': np.float64(0.0),
 'column': np.float64(0.0),
 'columns': np.float64(0.0),
 'com': np.float64(0.0),
 'command': np.float64(0.0),
 'commands': np.float64(0.0),
 'commit': np.float64(0.0),
 'common': np.float64(0.0),
 'community': np.float64(0.0),
 'compatibility': np.float64(0.0),
 'compatible': np.float64(0.0),
 'complete': np.float64(0.0),
 'completed': np.float64(0.0),
 'compose': np.float64(0.0),
 'compute': np.float64(0.0),
 'computer': np.float64(0.0),
 'conda': np.float64(0.0),
 'config': np.float64(0.0),
 'configuration': np.float64(0.0),
 'configure': np.float64(0.0),
 'configured': np.float64(0.0),
 'confirm': np.float64(0.0),
 'connect': np.float64(0.0),
 'connecting': np.float64(0.0),
 'connection': np.float64(0.0),
 'connector': np.float64(0.0),
 'consider': np.float64(0.0),
 'consistent': np.float64(0.0),
 'console': np.float64(0.0),
 'contain': np.float64(0.0),
 'container': np.float64(0.0),
 'containers': np.float64(0.0),
 'contains': np.float64(0.0),
 'content': np.float64(0.0),
 'contents': np.float64(0.0),
 'context': np.float64(0.0),
 'continue': np.float64(0.0),
 'control': np.float64(0.0),
 'convert': np.float64(0.0),
 'converted': np.float64(0.0),
 'copy': np.float64(0.0),
 'core': np.float64(0.0),
 'correct': np.float64(0.0),
 'correctly': np.float64(0.0),
 'correlation': np.float64(0.0),
 'corresponding': np.float64(0.0),
 'couldn': np.float64(0.0),
 'course': np.float64(0.0),
 'cp': np.float64(0.0),
 'cpu': np.float64(0.0),
 'create': np.float64(0.0),
 'create_engine': np.float64(0.0),
 'created': np.float64(0.0),
 'creates': np.float64(0.0),
 'creating': np.float64(0.0),
 'creation': np.float64(0.0),
 'credentials': np.float64(0.0),
 'credit': np.float64(0.0),
 'crucial': np.float64(0.0),
 'csv': np.float64(0.0),
 'ctrl': np.float64(0.0),
 'curl': np.float64(0.0),
 'current': np.float64(0.0),
 'custom': np.float64(0.0),
 'd37ci6vzurychx': np.float64(0.0),
 'daemon': np.float64(0.0),
 'daniel': np.float64(0.0),
 'dashboard': np.float64(0.0),
 'data': np.float64(0.3127766226016382),
 'database': np.float64(0.0),
 'dataframe': np.float64(0.0),
 'dataframes': np.float64(0.0),
 'dataproc': np.float64(0.0),
 'dataset': np.float64(0.0),
 'datasets': np.float64(0.0),
 'datatalks': np.float64(0.0),
 'datatalksclub': np.float64(0.5316383823591385),
 'datatype': np.float64(0.0),
 'date': np.float64(0.0),
 'datetime': np.float64(0.0),
 'david': np.float64(0.0),
 'day': np.float64(0.0),
 'db': np.float64(0.0),
 'dbt': np.float64(0.0),
 'dbt_project': np.float64(0.0),
 'deadline': np.float64(0.0),
 'dealing': np.float64(0.0),
 'debian': np.float64(0.0),
 'debug': np.float64(0.0),
 'deep': np.float64(0.0),
 'def': np.float64(0.0),
 'default': np.float64(0.0),
 'define': np.float64(0.0),
 'defined': np.float64(0.0),
 'definition': np.float64(0.0),
 'delete': np.float64(0.0),
 'deleted': np.float64(0.0),
 'deleting': np.float64(0.0),
 'denied': np.float64(0.0),
 'dependencies': np.float64(0.0),
 'dependency': np.float64(0.0),
 'deploy': np.float64(0.0),
 'deploying': np.float64(0.0),
 'deployment': np.float64(0.0),
 'deprecated': np.float64(0.0),
 'description': np.float64(0.0),
 'desktop': np.float64(0.0),
 'detailed': np.float64(0.0),
 'details': np.float64(0.0),
 'dev': np.float64(0.0),
 'development': np.float64(0.0),
 'deviation': np.float64(0.0),
 'device': np.float64(0.0),
 'df': np.float64(0.0),
 'df_train': np.float64(0.0),
 'dict': np.float64(0.0),
 'dictionary': np.float64(0.0),
 'dictvectorizer': np.float64(0.0),
 'did': np.float64(0.0),
 'didn': np.float64(0.0),
 'difference': np.float64(0.0),
 'different': np.float64(0.0),
 'dino': np.float64(0.0),
 'dir': np.float64(0.0),
 'directly': np.float64(0.0),
 'directory': np.float64(0.0),
 'disk': np.float64(0.0),
 'distribution': np.float64(0.0),
 'doc': np.float64(0.0),
 'docker': np.float64(0.0),
 'dockerfile': np.float64(0.0),
 'docs': np.float64(0.0),
 'document': np.float64(0.0),
 'documentation': np.float64(0.0),
 'does': np.float64(0.0),
 'doesn': np.float64(0.0),
 'doing': np.float64(0.0),
 'dolocationid': np.float64(0.0),
 'don': np.float64(0.0),
 'dot': np.float64(0.0),
 'double': np.float64(0.0),
 'downgrade': np.float64(0.0),
 'download': np.float64(0.0),
 'downloaded': np.float64(0.0),
 'downloading': np.float64(0.0),
 'downloads': np.float64(0.0),
 'dpage': np.float64(0.0),
 'dragon': np.float64(0.0),
 'drive': np.float64(0.0),
 'drop': np.float64(0.0),
 'dropoff_datetime': np.float64(0.0),
 'dropping': np.float64(0.0),
 'dt': np.float64(0.0),
 'dtc': np.float64(0.0),
 'duration': np.float64(0.0),
 'dv': np.float64(0.0),
 'easier': np.float64(0.0),
 'easiest': np.float64(0.0),
 'easily': np.float64(0.0),
 'ec2': np.float64(0.0),
 'echo': np.float64(0.0),
 'ecr': np.float64(0.0),
 'edit': np.float64(0.0),
 'editing': np.float64(0.0),
 'editor': np.float64(0.0),
 'email': np.float64(0.0),
 'en': np.float64(0.0),
 'enable': np.float64(0.0),
 'enabled': np.float64(0.0),
 'encode': np.float64(0.0),
 'encoding': np.float64(0.0),
 'encounter': np.float64(0.0),
 'encountered': np.float64(0.0),
 'end': np.float64(0.0),
 'endpoint': np.float64(0.0),
 'engine': np.float64(0.0),
 'engineering': np.float64(0.5401030373894639),
 'ensure': np.float64(0.0),
 'enter': np.float64(0.0),
 'entire': np.float64(0.0),
 'entries': np.float64(0.0),
 'env': np.float64(0.0),
 'environ': np.float64(0.0),
 'environment': np.float64(0.0),
 'environments': np.float64(0.0),
 'equal': np.float64(0.0),
 'erick': np.float64(0.0),
 'error': np.float64(0.0),
 'errors': np.float64(0.0),
 'escape': np.float64(0.0),
 'especially': np.float64(0.0),
 'eu': np.float64(0.0),
 'europe': np.float64(0.0),
 'evaluate': np.float64(0.0),
 'evaluated': np.float64(0.0),
 'evaluation': np.float64(0.0),
 'exactly': np.float64(0.0),
 'example': np.float64(0.0),
 'exception': np.float64(0.0),
 'exe': np.float64(0.0),
 'exec': np.float64(0.0),
 'executable': np.float64(0.0),
 'execute': np.float64(0.0),
 'executed': np.float64(0.0),
 'executing': np.float64(0.0),
 'execution': np.float64(0.0),
 'exist': np.float64(0.0),
 'existing': np.float64(0.0),
 'exists': np.float64(0.0),
 'exit': np.float64(0.0),
 'expected': np.float64(0.0),
 'experiment': np.float64(0.0),
 'explanation': np.float64(0.0),
 'explicitly': np.float64(0.0),
 'export': np.float64(0.0),
 'extension': np.float64(0.0),
 'external': np.float64(0.0),
 'extra': np.float64(0.0),
 'extract': np.float64(0.0),
 'face': np.float64(0.0),
 'faced': np.float64(0.0),
 'fact': np.float64(0.0),
 'fact_trips': np.float64(0.0),
 'fail': np.float64(0.0),
 'failed': np.float64(0.0),
 'failing': np.float64(0.0),
 'fails': np.float64(0.0),
 'false': np.float64(0.0),
 'faq': np.float64(0.0),
 'fatal': np.float64(0.0),
 'feature': np.float64(0.0),
 'features': np.float64(0.0),
 'fetch': np.float64(0.0),
 'fhv': np.float64(0.0),
 'fhv_tripdata_2019': np.float64(0.0),
 'field': np.float64(0.0),
 'figure': np.float64(0.0),
 'file': np.float64(0.0),
 'files': np.float64(0.0),
 'filesystem': np.float64(0.0),
 'filter': np.float64(0.0),
 'final': np.float64(0.0),
 'finally': np.float64(0.0),
 'findspark': np.float64(0.0),
 'fine': np.float64(0.0),
 'fit': np.float64(0.0),
 'fix': np.float64(0.0),
 'fixed': np.float64(0.0),
 'flag': np.float64(0.0),
 'flask': np.float64(0.0),
 'float': np.float64(0.0),
 'float64': np.float64(0.0),
 'flow': np.float64(0.0),
 'folder': np.float64(0.0),
 'folders': np.float64(0.0),
 'follow': np.float64(0.0),
 'followed': np.float64(0.0),
 'following': np.float64(0.0),
 'follows': np.float64(0.0),
 'forbidden': np.float64(0.0),
 'force': np.float64(0.0),
 'forget': np.float64(0.0),
 'forgot': np.float64(0.0),
 'form': np.float64(0.0),
 'format': np.float64(0.0),
 'forms': np.float64(0.0),
 'forward': np.float64(0.0),
 'fouesnard': np.float64(0.0),
 'free': np.float64(0.0),
 'fresh': np.float64(0.0),
 'fs': np.float64(0.0),
 'function': np.float64(0.0),
 'functions': np.float64(0.0),
 'future': np.float64(0.0),
 'gateway': np.float64(0.0),
 'gcloud': np.float64(0.0),
 'gcp': np.float64(0.0),
 'gcs': np.float64(0.0),
 'generate': np.float64(0.0),
 'generated': np.float64(0.0),
 'generator': np.float64(0.0),
 'george': np.float64(0.0),
 'get_dummies': np.float64(0.0),
 'get_feature_names_out': np.float64(0.0),
 'getdbt': np.float64(0.0),
 'getorcreate': np.float64(0.0),
 'gets': np.float64(0.0),
 'getting': np.float64(0.0),
 'git': np.float64(0.0),
 'github': np.float64(0.3792268345828722),
 'githubusercontent': np.float64(0.0),
 'gitignore': np.float64(0.0),
 'given': np.float64(0.0),
 'gives': np.float64(0.0),
 'gmail': np.float64(0.0),
 'going': np.float64(0.0),
 'good': np.float64(0.0),
 'google': np.float64(0.0),
 'google_application_credentials': np.float64(0.0),
 'googleapi': np.float64(0.0),
 'googleapis': np.float64(0.0),
 'got': np.float64(0.0),
 'gpu': np.float64(0.0),
 'great': np.float64(0.0),
 'green': np.float64(0.0),
 'grigorev': np.float64(0.0),
 'group': np.float64(0.0),
 'gs': np.float64(0.0),
 'guide': np.float64(0.0),
 'gunicorn': np.float64(0.0),
 'gz': np.float64(0.0),
 'gzip': np.float64(0.0),
 'hadoop': np.float64(0.0),
 'hadoop3': np.float64(0.0),
 'hand': np.float64(0.0),
 'handle': np.float64(0.0),
 'happen': np.float64(0.0),
 'happens': np.float64(0.0),
 'haven': np.float64(0.0),
 'having': np.float64(0.0),
 'head': np.float64(0.0),
 'help': np.float64(0.0),
 'helped': np.float64(0.0),
 'helps': np.float64(0.0),
 'high': np.float64(0.0),
 'higher': np.float64(0.0),
 'highly': np.float64(0.0),
 'home': np.float64(0.0),
 'homebrew': np.float64(0.0),
 'homework': np.float64(0.0),
 'homeworks': np.float64(0.0),
 'hope': np.float64(0.0),
 'host': np.float64(0.0),
 'hostname': np.float64(0.0),
 'hot': np.float64(0.0),
 'hours': np.float64(0.0),
 'housing': np.float64(0.0),
 'hrithik': np.float64(0.0),
 'html': np.float64(0.0),
 'http': np.float64(0.0),
 'https': np.float64(0.0),
 'humberto': np.float64(0.0),
 'hw': np.float64(0.0),
 'hws': np.float64(0.0),
 'iam': np.float64(0.0),
 'icon': np.float64(0.0),
 'id': np.float64(0.0),
 'ide': np.float64(0.0),
 'idea': np.float64(0.0),
 'ignore': np.float64(0.0),
 'image': np.float64(0.0),
 'images': np.float64(0.0),
 'immediately': np.float64(0.0),
 'import': np.float64(0.0),
 'importance': np.float64(0.0),
 'important': np.float64(0.0),
 'importerror': np.float64(0.0),
 'importing': np.float64(0.0),
 'include': np.float64(0.0),
 'included': np.float64(0.0),
 'including': np.float64(0.0),
 'increase': np.float64(0.0),
 'index': np.float64(0.0),
 'info': np.float64(0.0),
 'information': np.float64(0.0),
 'init': np.float64(0.0),
 'initial': np.float64(0.0),
 'input': np.float64(0.0),
 'inside': np.float64(0.0),
 'install': np.float64(0.0),
 'installation': np.float64(0.0),
 'installed': np.float64(0.0),
 'installing': np.float64(0.0),
 'instance': np.float64(0.0),
 'instances': np.float64(0.0),
 'instead': np.float64(0.0),
 'instruction': np.float64(0.0),
 'instructions': np.float64(0.0),
 'insufficient': np.float64(0.0),
 'int': np.float64(0.0),
 'int64': np.float64(0.0),
 'integer': np.float64(0.0),
 'interesting': np.float64(0.0),
 'interface': np.float64(0.0),
 'internal': np.float64(0.0),
 'internet': np.float64(0.0),
 'interpreter': np.float64(0.0),
 'intro': np.float64(0.0),
 'invalid': np.float64(0.0),
 'io': np.float64(0.0),
 'ip': np.float64(0.0),
 'ipynb': np.float64(0.0),
 'isn': np.float64(0.0),
 'issue': np.float64(0.0),
 'issues': np.float64(0.0),
 'iteration': np.float64(0.0),
 'ivan': np.float64(0.0),
 'jan': np.float64(0.0),
 'jar': np.float64(0.0),
 'java': np.float64(0.0),
 'java_home': np.float64(0.0),
 'job': np.float64(0.0),
 'jobs': np.float64(0.0),
 'join': np.float64(0.0),
 'json': np.float64(0.0),
 'jupyter': np.float64(0.0),
 'just': np.float64(0.0),
 'kafka': np.float64(0.0),
 'kaggle': np.float64(0.0),
 'keras': np.float64(0.0),
 'kernel': np.float64(0.0),
 'key': np.float64(0.0),
 'keys': np.float64(0.0),
 'kill': np.float64(0.0),
 'kind': np.float64(0.0),
 'kinesis': np.float64(0.0),
 'kniazeva': np.float64(0.0),
 'know': np.float64(0.0),
 'known': np.float64(0.0),
 'konrad': np.float64(0.0),
 'krishna': np.float64(0.0),
 'kubectl': np.float64(0.0),
 'kubernetes': np.float64(0.0),
 'kumar': np.float64(0.0),
 'kwargs': np.float64(0.0),
 'lambda': np.float64(0.0),
 'laptop': np.float64(0.0),
 'large': np.float64(0.0),
 'larkin': np.float64(0.0),
 'later': np.float64(0.0),
 'latest': np.float64(0.0),
 'launch': np.float64(0.0),
 'layer': np.float64(0.0),
 'layers': np.float64(0.0),
 'lead': np.float64(0.0),
 'leaderboard': np.float64(0.0),
 'learn': np.float64(0.0),
 'learning': np.float64(0.0),
 'left': np.float64(0.0),
 'length': np.float64(0.0),
 'lesson': np.float64(0.0),
 'lessons': np.float64(0.0),
 'let': np.float64(0.0),
 'level': np.float64(0.0),
 'lib': np.float64(0.0),
 'libraries': np.float64(0.0),
 'library': np.float64(0.0),
 'like': np.float64(0.0),
 'likely': np.float64(0.0),
 'line': np.float64(0.0),
 'linear': np.float64(0.0),
 'lines': np.float64(0.0),
 'link': np.float64(0.0),
 'links': np.float64(0.0),
 'linux': np.float64(0.0),
 'list': np.float64(0.0),
 'listed': np.float64(0.0),
 'litvinov': np.float64(0.0),
 'live': np.float64(0.0),
 'll': np.float64(0.0),
 'load': np.float64(0.0),
 'loaded': np.float64(0.0),
 'loading': np.float64(0.0),
 'local': np.float64(0.0),
 'localhost': np.float64(0.0),
 'locally': np.float64(0.0),
 'located': np.float64(0.0),
 'location': np.float64(0.0),
 'locations': np.float64(0.0),
 'lock': np.float64(0.0),
 'log': np.float64(0.0),
 'logged': np.float64(0.0),
 'login': np.float64(0.0),
 'logistic': np.float64(0.0),
 'logs': np.float64(0.0),
 'long': np.float64(0.0),
 'longer': np.float64(0.0),

In [80]:
df_qd = pd.DataFrame([query_dict, doc_dict], index=['query', 'doc']).T

(df_qd['query'] * df_qd['doc']).sum()

np.float64(0.0)

In [84]:
X.dot(q.T).todense()

matrix([[0.19464486],
        [0.        ],
        [0.        ],
        [0.06011641],
        [0.04932915],
        [0.        ],
        [0.        ],
        [0.13477565],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.15899187],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.07431408],
        [0.        ],
        [0.        ],
        [0.05779673],
        [0.07243428],
        [0.        ],
        [0.05174293],
        [0.16373635],
        [0.08076031],
        [0.        ],
        [0.09755254],
        [0.        ],
        [0.21069625],
        [0.12067781],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.06381749],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.00910541],
        [0.02835681],
        [0.05480112],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.02469964],
        [0.05129386],
        [0.06013439],
        [0.05252658],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.04169018],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.0075293 ],
        [0.        ],
        [0.        ],
        [0.01971463],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.032858  ],
        [0.        ],
        [0.01747343],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.01702162],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.02473889],
        [0.02946312],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.01165123],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.10175021],
        [0.01131942],
        [0.00931155],
        [0.116062  ],
        [0.        ],
        [0.08723274],
        [0.02364667],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.01879773],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.01120378],
        [0.        ],
        [0.0343277 ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.01903626],
        [0.05751914],
        [0.        ],
        [0.08382754],
        [0.02869786],
        [0.01648424],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.0256961 ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.09688353],
        [0.        ],
        [0.04097802],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.042196  ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.03504372],
        [0.01243893],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.03114757],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.02232588],
        [0.        ],
        [0.0157991 ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.03702031],
        [0.0519195 ],
        [0.        ],
        [0.        ],
        [0.03886889],
        [0.        ],
        [0.03381496],
        [0.        ],
        [0.        ],
        [0.01486219],
        [0.        ],
        [0.01714622],
        [0.        ],
        [0.03840903],
        [0.07197144],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.01823628],
        [0.12008449],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.02560741],
        [0.        ],
        [0.        ],
        [0.02601027],
        [0.        ],
        [0.        ],
        [0.01008179],
        [0.113943  ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.03172946],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.03260081],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.02649871],
        [0.        ],
        [0.01541203],
        [0.07064244],
        [0.        ],
        [0.03642018],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.10058179],
        [0.        ],
        [0.        ],
        [0.01434237],
        [0.        ],
        [0.04353931],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.02390443],
        [0.        ],
        [0.03120172],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.05775345],
        [0.0099719 ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.07385564],
        [0.        ],
        [0.02140465],
        [0.0175774 ],
        [0.01865718],
        [0.02364359],
        [0.        ],
        [0.02538317],
        [0.        ],
        [0.02361684],
        [0.        ],
        [0.01616171],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.03062796],
        [0.14833225],
        [0.0591534 ],
        [0.04586179],
        [0.03136018],
        [0.09991532],
        [0.04758541],
        [0.04819103],
        [0.        ],
        [0.04381424],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.01951173],
        [0.00853542],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.05570797],
        [0.1441334 ],
        [0.        ],
        [0.00826645],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.02490159],
        [0.        ],
        [0.        ],
        [0.01456942],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.02404658],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.08919246],
        [0.12564114],
        [0.04898763],
        [0.04877603],
        [0.        ],
        [0.        ],
        [0.08159364],
        [0.        ],
        [0.        ],
        [0.13862763],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.18388254],
        [0.        ],
        [0.        ],
        [0.02544166],
        [0.        ],
        [0.04071588],
        [0.12652136],
        [0.09276633],
        [0.13218047],
        [0.        ],
        [0.20274785],
        [0.        ],
        [0.        ],
        [0.04788151],
        [0.        ],
        [0.01972382],
        [0.        ],
        [0.        ],
        [0.04034157],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.06906424],
        [0.        ],
        [0.03940886],
        [0.        ],
        [0.01504532],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.03261805],
        [0.04412081],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.08727516],
        [0.        ],
        [0.09312669],
        [0.00720998],
        [0.09664266],
        [0.15074112],
        [0.        ],
        [0.0379524 ],
        [0.04650792],
        [0.15678262],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.36726645],
        [0.0384367 ],
        [0.        ],
        [0.02126985],
        [0.17870287],
        [0.09450339],
        [0.10444797],
        [0.17083833],
        [0.        ],
        [0.08317887],
        [0.17975705],
        [0.02967002],
        [0.138812  ],
        [0.03877046],
        [0.09628611],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.0353412 ],
        [0.08719701],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.02931901],
        [0.03784045],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.02272991],
        [0.02456984],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.09285679],
        [0.        ],
        [0.04019997],
        [0.03737611],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.08173022],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.10809817],
        [0.02848313],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.06560769],
        [0.        ],
        [0.0463972 ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.02952183],
        [0.04926297],
        [0.01890813],
        [0.        ],
        [0.02818665],
        [0.        ],
        [0.08856153],
        [0.        ],
        [0.04166996],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.02483496],
        [0.        ],
        [0.        ],
        [0.0285146 ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.11054182],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.02240511],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.25243151],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.05032042],
        [0.0733737 ],
        [0.01806383],
        [0.        ],
        [0.17328819],
        [0.04373237],
        [0.04530848],
        [0.        ],
        [0.        ],
        [0.19453521],
        [0.        ],
        [0.01087721],
        [0.02011193],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.01480609],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.05986488],
        [0.14536062],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.03195076],
        [0.        ],
        [0.06744665],
        [0.02474558],
        [0.        ],
        [0.        ],
        [0.03802815],
        [0.05237802],
        [0.01188471],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.03276737],
        [0.        ],
        [0.        ],
        [0.02997445],
        [0.04052286],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.0479318 ],
        [0.        ],
        [0.        ],
        [0.07631832],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.01294657],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.06069357],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.0398655 ],
        [0.03572417],
        [0.01832897],
        [0.06020736],
        [0.02443949],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.01084822],
        [0.02765232],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.03921645],
        [0.03286687],
        [0.        ],
        [0.        ],
        [0.03450939],
        [0.05044341],
        [0.        ],
        [0.04071622],
        [0.03378802],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.03028425],
        [0.        ],
        [0.        ],
        [0.03294593],
        [0.1091842 ],
        [0.        ],
        [0.03638289],
        [0.02172933],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.01313865],
        [0.05499111],
        [0.03813119],
        [0.04512243],
        [0.        ],
        [0.        ],
        [0.0405238 ],
        [0.08516359],
        [0.        ],
        [0.05643267],
        [0.        ],
        [0.        ],
        [0.01320149],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.07660932],
        [0.02211519],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.01846493],
        [0.        ],
        [0.06371533],
        [0.        ],
        [0.        ],
        [0.05740848],
        [0.        ],
        [0.01393189],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.01568811],
        [0.01216644],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.05427945],
        [0.04327458],
        [0.        ],
        [0.        ],
        [0.02830792],
        [0.        ],
        [0.20516901],
        [0.05758741],
        [0.        ],
        [0.03128986],
        [0.08547609],
        [0.        ],
        [0.        ],
        [0.09808762],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.02765396],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.04218829],
        [0.        ],
        [0.        ],
        [0.02696987],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.03152631],
        [0.        ],
        [0.15614104],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.16622367],
        [0.02264079],
        [0.02776126],
        [0.05193239],
        [0.24933816],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.04862107],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.09737658],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.09619256],
        [0.        ],
        [0.        ],
        [0.02821824],
        [0.        ],
        [0.03205008],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.01888311],
        [0.        ],
        [0.11394803],
        [0.04181344],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.08078146],
        [0.        ],
        [0.01802585],
        [0.02427599],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.07396627],
        [0.        ],
        [0.        ],
        [0.03569485],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.03870082],
        [0.03244106],
        [0.00829396],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.02534399],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.02225404],
        [0.04005687],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.04088559],
        [0.0115955 ],
        [0.        ],
        [0.04207585],
        [0.02006753],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.14087012],
        [0.        ],
        [0.04197403],
        [0.        ],
        [0.        ],
        [0.01586138],
        [0.02862402],
        [0.05749489],
        [0.05546193],
        [0.0333174 ],
        [0.03150482],
        [0.07032906],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.01971244],
        [0.        ],
        [0.        ],
        [0.07008363],

In [87]:
cosine_similarity(X, q).flatten()

array([0.19464486, 0.        , 0.        , 0.06011641, 0.04932915,
       0.        , 0.        , 0.13477565, 0.        , 0.        ,
       0.        , 0.15899187, 0.        , 0.        , 0.        ,
       0.07431408, 0.        , 0.        , 0.05779673, 0.07243428,
       0.        , 0.05174293, 0.16373635, 0.08076031, 0.        ,
       0.09755254, 0.        , 0.21069625, 0.12067781, 0.        ,
       0.        , 0.        , 0.        , 0.06381749, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.00910541,
       0.02835681, 0.05480112, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.02469964, 0.05129386, 0.06013439,
       0.05252658, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.04169018, 0.        , 0.        , 0.        , 0.0075293 ,
       0.        , 0.        , 0.01971463, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.032858  , 0.        , 0.01747343, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.01702162,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.02473889, 0.02946312, 0.        , 0.        , 0.        ,
       0.        , 0.01165123, 0.        , 0.        , 0.        ,
       0.10175021, 0.01131942, 0.00931155, 0.116062  , 0.        ,
       0.08723274, 0.02364667, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.01879773, 0.        , 0.        ,
       0.        , 0.01120378, 0.        , 0.0343277 , 0.        ,
       0.        , 0.        , 0.01903626, 0.05751914, 0.        ,
       0.08382754, 0.02869786, 0.01648424, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.0256961 , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.09688353, 0.        ,
       0.04097802, 0.        , 0.        , 0.        , 0.042196  ,
       0.        , 0.        , 0.        , 0.03504372, 0.01243893,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.03114757, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.02232588, 0.        , 0.0157991 ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.03702031, 0.0519195 , 0.        , 0.        , 0.03886889,
       0.        , 0.03381496, 0.        , 0.        , 0.01486219,
       0.        , 0.01714622, 0.        , 0.03840903, 0.07197144,
       0.        , 0.        , 0.        , 0.01823628, 0.12008449,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.02560741, 0.        , 0.        ,
       0.02601027, 0.        , 0.        , 0.01008179, 0.113943  ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.03172946, 0.        , 0.        , 0.        ,
       0.        , 0.03260081, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.02649871, 0.        ,
       0.01541203, 0.07064244, 0.        , 0.03642018, 0.        ,
       0.        , 0.        , 0.10058179, 0.        , 0.        ,
       0.01434237, 0.        , 0.04353931, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.02390443, 0.        , 0.03120172, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.05775345, 0.0099719 , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.07385564,
       0.        , 0.02140465, 0.0175774 , 0.01865718, 0.02364359,
       0.        , 0.02538317, 0.        , 0.02361684, 0.        ,
       0.01616171, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.03062796, 0.14833225,
       0.0591534 , 0.04586179, 0.03136018, 0.09991532, 0.04758541,
       0.04819103, 0.        , 0.04381424, 0.        , 0.        ,
       0.        , 0.        , 0.01951173, 0.00853542, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.05570797, 0.1441334 , 0.        ,
       0.00826645, 0.        , 0.        , 0.        , 0.        ,
       0.02490159, 0.        , 0.        , 0.01456942, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.02404658,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.08919246, 0.12564114, 0.04898763,
       0.04877603, 0.        , 0.        , 0.08159364, 0.        ,
       0.        , 0.13862763, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.18388254, 0.        ,
       0.        , 0.02544166, 0.        , 0.04071588, 0.12652136,
       0.09276633, 0.13218047, 0.        , 0.20274785, 0.        ,
       0.        , 0.04788151, 0.        , 0.01972382, 0.        ,
       0.        , 0.04034157, 0.        , 0.        , 0.        ,
       0.        , 0.06906424, 0.        , 0.03940886, 0.        ,
       0.01504532, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.03261805,
       0.04412081, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.08727516, 0.        , 0.09312669, 0.00720998,
       0.09664266, 0.15074112, 0.        , 0.0379524 , 0.04650792,
       0.15678262, 0.        , 0.        , 0.        , 0.        ,
       0.36726645, 0.0384367 , 0.        , 0.02126985, 0.17870287,
       0.09450339, 0.10444797, 0.17083833, 0.        , 0.08317887,
       0.17975705, 0.02967002, 0.138812  , 0.03877046, 0.09628611,
       0.        , 0.        , 0.        , 0.        , 0.0353412 ,
       0.08719701, 0.        , 0.        , 0.        , 0.02931901,
       0.03784045, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.02272991,
       0.02456984, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.09285679, 0.        , 0.04019997, 0.03737611, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.08173022, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.10809817, 0.02848313, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.06560769,
       0.        , 0.0463972 , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.02952183,
       0.04926297, 0.01890813, 0.        , 0.02818665, 0.        ,
       0.08856153, 0.        , 0.04166996, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.02483496,
       0.        , 0.        , 0.0285146 , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.11054182, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.02240511, 0.        ,
       0.        , 0.        , 0.25243151, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.05032042, 0.0733737 , 0.01806383,
       0.        , 0.17328819, 0.04373237, 0.04530848, 0.        ,
       0.        , 0.19453521, 0.        , 0.01087721, 0.02011193,
       0.        , 0.        , 0.        , 0.01480609, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.05986488,
       0.14536062, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.03195076, 0.        , 0.06744665,
       0.02474558, 0.        , 0.        , 0.03802815, 0.05237802,
       0.01188471, 0.        , 0.        , 0.        , 0.03276737,
       0.        , 0.        , 0.02997445, 0.04052286, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.0479318 ,
       0.        , 0.        , 0.07631832, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.01294657, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.06069357, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.0398655 , 0.03572417, 0.01832897, 0.06020736, 0.02443949,
       0.        , 0.        , 0.        , 0.        , 0.01084822,
       0.02765232, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.03921645, 0.03286687, 0.        , 0.        ,
       0.03450939, 0.05044341, 0.        , 0.04071622, 0.03378802,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.03028425, 0.        , 0.        ,
       0.03294593, 0.1091842 , 0.        , 0.03638289, 0.02172933,
       0.        , 0.        , 0.        , 0.01313865, 0.05499111,
       0.03813119, 0.04512243, 0.        , 0.        , 0.0405238 ,
       0.08516359, 0.        , 0.05643267, 0.        , 0.        ,
       0.01320149, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.07660932, 0.02211519, 0.        , 0.        ,
       0.        , 0.01846493, 0.        , 0.06371533, 0.        ,
       0.        , 0.05740848, 0.        , 0.01393189, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.01568811,
       0.01216644, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.05427945, 0.04327458,
       0.        , 0.        , 0.02830792, 0.        , 0.20516901,
       0.05758741, 0.        , 0.03128986, 0.08547609, 0.        ,
       0.        , 0.09808762, 0.        , 0.        , 0.        ,
       0.02765396, 0.        , 0.        , 0.        , 0.04218829,
       0.        , 0.        , 0.02696987, 0.        , 0.        ,
       0.        , 0.        , 0.03152631, 0.        , 0.15614104,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.16622367, 0.02264079, 0.02776126,
       0.05193239, 0.24933816, 0.        , 0.        , 0.        ,
       0.04862107, 0.        , 0.        , 0.        , 0.09737658,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.09619256, 0.        , 0.        , 0.02821824,
       0.        , 0.03205008, 0.        , 0.        , 0.        ,
       0.01888311, 0.        , 0.11394803, 0.04181344, 0.        ,
       0.        , 0.        , 0.08078146, 0.        , 0.01802585,
       0.02427599, 0.        , 0.        , 0.        , 0.07396627,
       0.        , 0.        , 0.03569485, 0.        , 0.        ,
       0.        , 0.03870082, 0.03244106, 0.00829396, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.02534399, 0.        , 0.        , 0.        ,
       0.        , 0.02225404, 0.04005687, 0.        , 0.        ,
       0.        , 0.        , 0.04088559, 0.0115955 , 0.        ,
       0.04207585, 0.02006753, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.14087012,
       0.        , 0.04197403, 0.        , 0.        , 0.01586138,
       0.02862402, 0.05749489, 0.05546193, 0.0333174 , 0.03150482,
       0.07032906, 0.        , 0.        , 0.        , 0.        ,
       0.01971244, 0.        , 0.        , 0.07008363, 0.03250596,
       0.        , 0.        , 0.        , 0.        , 0.01636514,
       0.02240468, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.10990929,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.04226762, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.19910113, 0.        ,
       0.02007173, 0.07615327, 0.01941338, 0.        , 0.02889504,
       0.        , 0.        , 0.        ])